# Generated by Django 3.2.6 on 2023-07-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_number', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('contact_first_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(default=None, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(default=None, max_length=50, null=True)),
                ('postal_code', models.CharField(default=None, max_length=15, null=True)),
                ('country', models.CharField(max_length=50)),
                ('credit_limit', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50, null=True)),
                ('address_line_2', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=15, null=True)),
                ('territory', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('required_date', models.DateField()),
                ('shipped_date', models.DateField(default=None, null=True)),
                ('status', models.CharField(max_length=15)),
                ('comments', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic_models.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('product_line', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text_description', models.CharField(default=None, max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=70)),
                ('product_scale', models.CharField(max_length=10)),
                ('product_vendor', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('quantity_in_stock', models.PositiveSmallIntegerField()),
                ('buy_price', models.FloatField()),
                ('msrp', models.FloatField()),
                ('product_line', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='classic_models.productline')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_number', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=50)),
                ('office', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='classic_models.office')),
                ('reported_employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classic_models.employee')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_rep_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classic_models.employee'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classic_models.customer')),
            ],
            options={
                'unique_together': {('customer', 'check_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('price_each', models.FloatField()),
                ('order_line_number', models.SmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic_models.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic_models.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
