# Generated by Django 3.2.6 on 2023-07-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reported_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_employee', to='classic_models.employee'),
        ),
    ]
