# Generated by Django 3.2.6 on 2023-07-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_models', '0002_alter_employee_reported_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classic_models.customer', verbose_name='customer_number'),
        ),
    ]
